### ISSUE TITLE
actvationServer.py , ActivationClient.py missing 

### ISSUE THREAD

**Issue by tankisank** [Theviki20110/Features-Extractor#2]
instead of just putting the image upload the code

**Comment by Theviki20110** [comment]
RUN.py, activationServer and activationClient will be posted in a new repo.
RUN.py also needs four more scripts (HTTP, SSH, SMTP and SNMP) but they are out of topic in this repo.

**Comment by tankisank** [comment]
Yeah do post it , i want to know how those work , ur project is really good
😊

**Comment by tankisank** [comment]
> RUN.py, activationServer and activationClient will be posted in a new repo.
> RUN.py also needs four more scripts (HTTP, SSH, SMTP and SNMP) but they are out of topic in this repo.
> 

When are u planning to post into a separate repo? I am also doing a similar project based on http flood attacks with client server architecture it would be helpful for me if u could share it soon 🙂

**Comment by Theviki20110** [comment]
Maybe during this weekend.
I have to dockerize all VMs and generalize scripts.

**Comment by tankisank** [comment]
please upload the code by today 🤗

**Comment by Theviki20110** [comment]
Published in new branch.
I'll refactor them in a more general form.

**Comment by tankisank** [comment]
Great, thanks!
